#!/bin/bash
# setup-elastic.sh
# Installs and configures Elastic Agent to monitor Rural Care Connect.
# Run this AFTER docker compose up and AFTER the app is working.
#
# What this ships to Elastic Cloud:
#   - Container logs (backend API + nginx access logs) via Docker log driver
#   - System metrics (CPU, RAM, disk) for the Ubuntu host
#   - APM traces from the Node.js backend via OTEL
#   - Custom audit events as structured logs

set -euo pipefail

# ── Configuration — edit these before running ─────────────────────────
FLEET_URL="https://6b2204615f514e8d8a6613fada53ef11.fleet.us-east-2.aws.elastic-cloud.com:443"
ENROLLMENT_TOKEN="UzRfY3c1NEJTQnNQRHVBYVVoU2I6MWpTVE9fRjh1OFhjRGUtRlFSZ0R4UQ=="
ELASTIC_VERSION="9.4.2"

echo "═══════════════════════════════════════════════════════"
echo "  Rural Care Connect — Elastic Agent Setup"
echo "═══════════════════════════════════════════════════════"
echo ""

# ── Step 1: Download and install Elastic Agent ────────────────────────
echo "📥 Step 1: Installing Elastic Agent ${ELASTIC_VERSION}..."

if ! command -v elastic-agent &> /dev/null; then
  curl -sL -O "https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-${ELASTIC_VERSION}-linux-x86_64.tar.gz"
  tar xzf "elastic-agent-${ELASTIC_VERSION}-linux-x86_64.tar.gz"
  cd "elastic-agent-${ELASTIC_VERSION}-linux-x86_64"

  sudo ./elastic-agent install \
    --url="$FLEET_URL" \
    --enrollment-token="$ENROLLMENT_TOKEN" \
    --non-interactive

  cd ..
  echo "✅ Elastic Agent installed"
else
  echo "✅ Elastic Agent already installed — skipping"
fi

# ── Step 2: Write .env file for OTEL APM endpoint ────────────────────
echo ""
echo "🔧 Step 2: Configuring OTEL environment..."

# Extract APM endpoint from Fleet URL (replace fleet. prefix with apm.)
APM_SERVER_URL=$(echo "$FLEET_URL" | sed 's|fleet\.|apm.|' | sed 's|:443.*|:443|')

cat > /home/mike/rcc-demo/.env << ENVEOF
# Elastic APM / OTEL — sourced by docker-compose
# Generated by setup-elastic.sh — do not commit to git

ELASTIC_APM_SERVER_URL=${APM_SERVER_URL}
ELASTIC_APM_SECRET_TOKEN=${ENROLLMENT_TOKEN}

# These are passed to the backend container as OTEL env vars
OTEL_EXPORTER_OTLP_ENDPOINT=${APM_SERVER_URL}
OTEL_EXPORTER_OTLP_HEADERS=Authorization=Bearer ${ENROLLMENT_TOKEN}
ENVEOF

echo "✅ .env written to ~/rcc-demo/.env"
echo "   APM endpoint: $APM_SERVER_URL"

# ── Step 3: Add docker log collection to Elastic Agent ───────────────
echo ""
echo "📋 Step 3: Configuring Docker log collection..."

# Elastic Agent Fleet integration for Docker logs
# After enrollment, add the Docker integration via Fleet UI:
# Fleet → Integrations → Docker → Add Docker → configure as below

cat << 'DOCKER_HINT'
═══════════════════════════════════════════════════════
MANUAL STEP REQUIRED — Elastic Fleet UI
═══════════════════════════════════════════════════════
1. Open: https://cloud.elastic.co → Kibana → Fleet
2. Go to: Integrations → Add integration → search "Docker"
3. Add "Docker" integration with these settings:

   Collect container logs: ✅ enabled
   Container IDs / names (leave blank = collect all, or specify):
     - rcc_backend
     - rcc_frontend
     - rcc_db
     - rcc_ollama

   Collect container metrics: ✅ enabled
   Metrics period: 10s

4. Save and deploy to your agent policy.

This will ship:
  - All stdout/stderr from each container (JSON parsed)
  - CPU / memory / network per container
  - Docker daemon events
═══════════════════════════════════════════════════════
DOCKER_HINT

# ── Step 4: Install Node.js OTEL SDK in backend ───────────────────────
echo ""
echo "📦 Step 4: Installing OTEL SDK in backend..."

cd /home/mike/rcc-demo/backend

npm install --save \
  @opentelemetry/sdk-node \
  @opentelemetry/auto-instrumentations-node \
  @opentelemetry/exporter-trace-otlp-http \
  @opentelemetry/exporter-metrics-otlp-http \
  @opentelemetry/resources \
  @opentelemetry/semantic-conventions

echo "✅ OTEL packages installed"

# ── Step 5: Verify agent is running ──────────────────────────────────
echo ""
echo "🔍 Step 5: Verifying Elastic Agent status..."
sudo elastic-agent status | head -20

echo ""
echo "═══════════════════════════════════════════════════════"
echo "✅ Setup complete!"
echo ""
echo "Next steps:"
echo "  1. Complete the Fleet UI Docker integration (see Step 3 above)"
echo "  2. Restart docker compose: docker compose down && docker compose up --build"
echo "  3. In Kibana → Observability → APM — look for 'rcc-backend'"
echo "  4. In Kibana → Discover — filter by service.name: rcc-backend"
echo "  5. In Kibana → Logs — filter by container.name: rcc_backend"
echo "═══════════════════════════════════════════════════════"
